language: php

php:
  - 7.2

install:
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p

notifications:
  email:
    recipients:
      - ghost0436@gmail.com
    on_success: always
    on_failure: always
